### ISSUE TITLE
java artifacts are not being deployed to nexus

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/jenkins-workflow-library#177]
this line here https://github.com/fabric8io/jenkins-pipeline-library/blob/master/vars/mavenCanaryRelease.groovy#L15 should be replaced with `mvn install deploy`

but there's an odd error thats started happening where the deploy phase cant find the local artifacts to send to nexus

**Comment by KurtStam** [comment]
This was fixed by changing the .m2/settings.xml:

https://github.com/fabric8io/fabric8-devops/issues/622
https://github.com/fabric8io/fabric8-devops/pull/623

We must have upgraded the maven version and this changed which altRepo was picked.
