### ISSUE TITLE
Document different groovy files

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/jenkins-workflow-library#3]
Document different groovy files; what they are doing, steps of the workflow, ... 

```
CanaryRelease.groovy
CanaryReleaseAndStage.groovy
CanaryReleaseStageAndApprovePromote.groovy
Deploy.groovy
Fabric8Release.groovy
Fabric8ReleaseTest.groovy
Install.groovy
```

What means Canary ?

**Comment by christian-posta** [comment]
http://martinfowler.com/bliki/CanaryRelease.html

And differences

http://blog.christianposta.com/deploy/blue-green-deployments-a-b-testing-and-canary-releases/

On Monday, September 7, 2015, Charles Moulliard notifications@github.com
wrote:

> Document different groovy files; what they are doing, steps of the
> workflow, ...
> 
> CanaryRelease.groovy
> CanaryReleaseAndStage.groovy
> CanaryReleaseStageAndApprovePromote.groovy
> Deploy.groovy
> Fabric8Release.groovy
> Fabric8ReleaseTest.groovy
> Install.groovy
> 
> What means Canary ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fabric8io/jenkins-workflow-library/issues/3.

## 

_Christian Posta_
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by cmoulliard** [comment]
Thx Christian. I will update the doc based on your input and also document
the variations proposed

On Mon, Sep 7, 2015 at 10:21 PM, Christian Posta notifications@github.com
wrote:

> http://martinfowler.com/bliki/CanaryRelease.html
> 
> And differences
> 
> http://blog.christianposta.com/deploy/blue-green-deployments-a-b-testing-and-canary-releases/
> 
> On Monday, September 7, 2015, Charles Moulliard notifications@github.com
> wrote:
> 
> > Document different groovy files; what they are doing, steps of the
> > workflow, ...
> > 
> > CanaryRelease.groovy
> > CanaryReleaseAndStage.groovy
> > CanaryReleaseStageAndApprovePromote.groovy
> > Deploy.groovy
> > Fabric8Release.groovy
> > Fabric8ReleaseTest.groovy
> > Install.groovy
> > 
> > What means Canary ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fabric8io/jenkins-workflow-library/issues/3.
> 
> ## 
> 
> _Christian Posta_
> twitter: @christianposta
> http://www.christianposta.com/blog
> http://fabric8.io
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fabric8io/jenkins-workflow-library/issues/3#issuecomment-138370246
> .

## 

Charles Moulliard
Apache Committer / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by jstrachan** [comment]
Its on my list to refactor the library to switch from

```
maven/Foo.groovy
```

to

```
maven/Foo/Jenkinsfile
```

as the long term canonical name for a jenkins workflow file is `Jenkinsfile`. This also means we can then put a ReadMe.md into each folder to describe each workflow - along with optional images.

Though for describing things like Canary releases or whatever terms we use in the workflows, we probably want to add those to the fabric8io/fabric8/docs folder and just link to them as they will be used in multiple workflows

**Comment by jstrachan** [comment]
BTW part of the reason for the new ReadMe.md files are so that the create project / devops edit UI commands can render the markdown of the currently selected workflow. 

Ideally I'd love to be able to auto-generate a UI of the stages/flow too - but thats a bit harder...

**Comment by rafabene** [comment]
@jstrachan  +1 for this [planned refactoring](3#issuecomment-138592241). The current folder structures makes it hard to choose the right script and the purpose of each one.

**Comment by rawlingsj** [comment]
The workflow scripts 

```
CanaryRelease.groovy
CanaryReleaseAndStage.groovy
CanaryReleaseStageAndApprovePromote.groovy
```

need a bit of refactoring and made into reusable functions like the fabric8 release scripts..

```
hubot room: 'release', message: "release started"
try {

  releaseProject{
    project = 'fabric8'
    projectArtifact = 'io/fabric8/fabric8-maven-plugin'
  }

  hubot room: 'release', message: "release success"

} catch (err){
    hubot room: 'release', message: "fabric8 release failed ${err}"
    currentBuild.result = 'FAILURE'
}
```

I'll look at doing that this week and then switch to using `maven/Foo/Jenkinsfile` as well as adding the readme's.

**Comment by jstrachan** [comment]
@rawlingsj Cool! I guess its not a huge biggie if we do rename them to Jenkinsfile or not - if you copy them to a project we now rename the file to be called Jenkinsfile anyways. But I guess if each workflow had its own folder it'd be easier to have docs + images and stuff more obviously related to the jenkins file. For now we could use Foo.groovy and Foo.md or something.

**Comment by rawlingsj** [comment]
functions now documented https://github.com/fabric8io/jenkins-workflow-library/commit/c7259fc6f01a6942ab144c7decb2542f2f34c826 and Jenkinsfile rename happened a little while ago.
