### ISSUE TITLE
unable to resolve class io.fabric8.Fabric8Commands

### ISSUE THREAD

**Issue by caselogic16** [fabric8io/jenkins-workflow-library#60]
While the Jenkins workflow script "jenkins-workflow-library/maven/CanaryReleaseStageAndApprovePromote.groovy" runs, the following error is encountered: 

WorkflowScript: 29: unable to resolve class io.fabric8.Fabric8Commands 
 @ line 29, column 16.
       def flow = new io.fabric8.Fabric8Commands()

How can this error be resolved in Jenkins?

**Comment by rawlingsj** [comment]
It's been a while, sorry @dennis-ups I'd not noticed the issue till now - my bad.

Are you still using this library? I'm hoping the issue should have been fixed as we've been using that pipeline reliably for a while now.

**Comment by rajdavies** [comment]
this should be fixed
