### ISSUE TITLE
CanaryRelease pipeline can be run only once

### ISSUE THREAD

**Issue by ThomaciousD** [fabric8io/jenkins-workflow-library#90]
When choosing CanaryPipeline.groovy from the pipeline lists in fabric8, it can be run only once.

Main reason: the "git checkout -b " command fails as the branch already exists.

Why: because the version number in the branch name is null. This version number comes from the canaryVersion variable used in the workflow, which is not initialized.

How to reproduce:
- under fabric8, create a new project
- select CanaryRelease.groovy pipeline
- execute the pipeline -> should be fine
- execute the pipeline again -> should fail for the following reason: fatal: A branch named '_project_name_-null' already exists.

Workaround:
- edit the file Jenkinsfile at the root of your project.
- insert the following code before `node ('kubernetes'){` :

`def canaryVersion = "${versionPrefix}.${env.BUILD_NUMBER}"`

**Comment by rawlingsj** [comment]
Ah good catch!  I wonder if we can use the versionPrefix above instead?  I think that's what's supposed to be used but lost during a copy / paste. https://github.com/fabric8io/jenkins-workflow-library/blob/master/workflows/maven/CanaryRelease/Jenkinsfile#L3

**Comment by rawlingsj** [comment]
scrap my last comment yeah `def canaryVersion = "${versionPrefix}.${env.BUILD_NUMBER}"` should do it. 

Fancy submitting a PR @Tomtom76?
